FROM maven:3.5-jdk-8

COPY ./ /spring-cloud-ergouzi
RUN chmod a+x /spring-cloud-ergouzi/eureka-server/entrypoint.sh
EXPOSE 8761
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone
WORKDIR /spring-cloud-ergouzi/eureka-server/
CMD /spring-cloud-ergouzi/eureka-server/entrypoint.sh pro
