FROM maven:3.5-jdk-8

COPY ./ /spring-cloud-ergouzi
RUN chmod a+x /spring-cloud-ergouzi/eureka-server/entrypoint.sh
EXPOSE 8761
WORKDIR /spring-cloud-ergouzi/eureka-server/
CMD /spring-cloud-ergouzi/eureka-server/entrypoint.sh pro

