server:
  port: 8762

spring:
  application:
    name: eureka-producer
  mvc:
    static-path-pattern: /images/*
  resources:
    static-locations: classpath:/static   #/spring-cloud-ergouzi/eureka-producer/target/static  # 高
eureka:
  instance:
    hostname: 172.27.173.240 #线上
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
