
server:
  port: 8763

spring:
  application:
    name: eureka-consumer

eureka:
  instance:
    hostname: 172.27.173.240 #线上
  #    hostname: 127.0.0.1 #本地
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/